#############################################################################
# Makefile for building: STB032_SPI
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  STB032_SPI.pro
# Template: app
# Command: /opt/Qt/5.15.2/gcc_64/bin/qmake -o Makefile STB032_SPI.pro -config release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_BLUETOOTH_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt/5.15.2/gcc_64/include -I/opt/Qt/5.15.2/gcc_64/include/QtWidgets -I/opt/Qt/5.15.2/gcc_64/include/QtGui -I/opt/Qt/5.15.2/gcc_64/include/QtBluetooth -I/opt/Qt/5.15.2/gcc_64/include/QtCore -I. -I/usr/include/libdrm -I. -I/opt/Qt/5.15.2/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt/5.15.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/Qt/5.15.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/Qt/5.15.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = STB032_SPI1.0.0
DISTDIR = /home/ben/STB032_SPI/.tmp/STB032_SPI1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt/5.15.2/gcc_64/lib -Wl,-rpath-link,/opt/Qt/5.15.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/ben/STB032_SPI/libMPSSE.a /home/ben/STB032_SPI/libftd2xx.a -ldl /opt/Qt/5.15.2/gcc_64/lib/libQt5Widgets.so /opt/Qt/5.15.2/gcc_64/lib/libQt5Gui.so /opt/Qt/5.15.2/gcc_64/lib/libQt5Bluetooth.so /opt/Qt/5.15.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ftdi_common.c \
		ftdi_i2c.c \
		ftdi_infra.c \
		ftdi_mid.c \
		ftdi_spi.c \
		mainwindow.cpp qrc_style.cpp \
		qrc_icons.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		ftdi_common.o \
		ftdi_i2c.o \
		ftdi_infra.o \
		ftdi_mid.o \
		ftdi_spi.o \
		mainwindow.o \
		qrc_style.o \
		qrc_icons.o \
		moc_mainwindow.o
DIST          = /opt/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		STB032_SPI.pro mainwindow.h \
		ftdi_common.h \
		ftdi_i2c.h \
		ftdi_infra.h \
		ftdi_mid.h \
		ftdi_spi.h \
		libMPSSE_spi.h main.cpp \
		ftdi_common.c \
		ftdi_i2c.c \
		ftdi_infra.c \
		ftdi_mid.c \
		ftdi_spi.c \
		mainwindow.cpp
QMAKE_TARGET  = STB032_SPI
DESTDIR       = 
TARGET        = STB032_SPI


first: all
####### Build rules

STB032_SPI: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: STB032_SPI.pro /opt/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		STB032_SPI.pro \
		qdarkstyle/dark/style.qrc \
		icons/icons.qrc
	$(QMAKE) -o Makefile STB032_SPI.pro -config release
/opt/Qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/qt.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/resources.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/moc.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/uic.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/5.15.2/gcc_64/mkspecs/features/lex.prf:
STB032_SPI.pro:
qdarkstyle/dark/style.qrc:
icons/icons.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile STB032_SPI.pro -config release

qmake_all: FORCE


all: Makefile STB032_SPI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qdarkstyle/dark/style.qrc icons/icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h ftdi_common.h ftdi_i2c.h ftdi_infra.h ftdi_mid.h ftdi_spi.h libMPSSE_spi.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp ftdi_common.c ftdi_i2c.c ftdi_infra.c ftdi_mid.c ftdi_spi.c mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_style.cpp qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_style.cpp qrc_icons.cpp
qrc_style.cpp: qdarkstyle/dark/style.qrc \
		/opt/Qt/5.15.2/gcc_64/bin/rcc \
		qdarkstyle/dark/rc/transparent.png \
		qdarkstyle/dark/rc/line_horizontal_pressed.png \
		qdarkstyle/dark/rc/line_horizontal.png \
		qdarkstyle/dark/rc/arrow_left_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more_focus.png \
		qdarkstyle/dark/rc/.keep \
		qdarkstyle/dark/rc/arrow_down_disabled@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_pressed.png \
		qdarkstyle/dark/rc/window_close_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_focus.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_pressed@2x.png \
		qdarkstyle/dark/rc/window_close_pressed.png \
		qdarkstyle/dark/rc/branch_open_disabled@2x.png \
		qdarkstyle/dark/rc/line_horizontal_focus@2x.png \
		qdarkstyle/dark/rc/checkbox_unchecked.png \
		qdarkstyle/dark/rc/radio_checked_focus@2x.png \
		qdarkstyle/dark/rc/checkbox_checked_pressed@2x.png \
		qdarkstyle/dark/rc/base_icon_disabled.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal.png \
		qdarkstyle/dark/rc/window_close_disabled.png \
		qdarkstyle/dark/rc/branch_line@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical@2x.png \
		qdarkstyle/dark/rc/arrow_right_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_disabled.png \
		qdarkstyle/dark/rc/checkbox_checked@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_focus.png \
		qdarkstyle/dark/rc/radio_unchecked_disabled.png \
		qdarkstyle/dark/rc/checkbox_indeterminate.png \
		qdarkstyle/dark/rc/window_close_disabled@2x.png \
		qdarkstyle/dark/rc/window_grip_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_focus@2x.png \
		qdarkstyle/dark/rc/branch_closed_disabled.png \
		qdarkstyle/dark/rc/branch_line.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_pressed.png \
		qdarkstyle/dark/rc/transparent_focus.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal.png \
		qdarkstyle/dark/rc/branch_end_focus.png \
		qdarkstyle/dark/rc/checkbox_unchecked@2x.png \
		qdarkstyle/dark/rc/window_undock_disabled.png \
		qdarkstyle/dark/rc/radio_checked_pressed@2x.png \
		qdarkstyle/dark/rc/branch_end_focus@2x.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_focus.png \
		qdarkstyle/dark/rc/arrow_left_focus.png \
		qdarkstyle/dark/rc/arrow_left@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_focus@2x.png \
		qdarkstyle/dark/rc/window_grip_focus@2x.png \
		qdarkstyle/dark/rc/window_undock_focus.png \
		qdarkstyle/dark/rc/window_close.png \
		qdarkstyle/dark/rc/line_horizontal@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical_focus@2x.png \
		qdarkstyle/dark/rc/arrow_right@2x.png \
		qdarkstyle/dark/rc/base_icon_pressed.png \
		qdarkstyle/dark/rc/branch_line_focus.png \
		qdarkstyle/dark/rc/window_grip_focus.png \
		qdarkstyle/dark/rc/arrow_right_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_disabled.png \
		qdarkstyle/dark/rc/arrow_up.png \
		qdarkstyle/dark/rc/arrow_left_pressed@2x.png \
		qdarkstyle/dark/rc/checkbox_checked.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_disabled.png \
		qdarkstyle/dark/rc/line_vertical_pressed.png \
		qdarkstyle/dark/rc/base_icon_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_focus.png \
		qdarkstyle/dark/rc/branch_end_pressed.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_focus@2x.png \
		qdarkstyle/dark/rc/window_minimize_disabled.png \
		qdarkstyle/dark/rc/window_undock_pressed.png \
		qdarkstyle/dark/rc/radio_checked@2x.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_disabled@2x.png \
		qdarkstyle/dark/rc/branch_closed_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical.png \
		qdarkstyle/dark/rc/branch_line_disabled.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical.png \
		qdarkstyle/dark/rc/branch_more_disabled.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal@2x.png \
		qdarkstyle/dark/rc/window_undock_disabled@2x.png \
		qdarkstyle/dark/rc/arrow_down_pressed.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical_focus.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal@2x.png \
		qdarkstyle/dark/rc/arrow_left_focus@2x.png \
		qdarkstyle/dark/rc/transparent_focus@2x.png \
		qdarkstyle/dark/rc/branch_open_focus@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_disabled@2x.png \
		qdarkstyle/dark/rc/arrow_down_focus@2x.png \
		qdarkstyle/dark/rc/arrow_up_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_disabled@2x.png \
		qdarkstyle/dark/rc/checkbox_checked_disabled.png \
		qdarkstyle/dark/rc/checkbox_checked_disabled@2x.png \
		qdarkstyle/dark/rc/line_vertical@2x.png \
		qdarkstyle/dark/rc/window_close@2x.png \
		qdarkstyle/dark/rc/arrow_right_disabled.png \
		qdarkstyle/dark/rc/branch_open@2x.png \
		qdarkstyle/dark/rc/checkbox_unchecked_focus@2x.png \
		qdarkstyle/dark/rc/line_vertical_disabled@2x.png \
		qdarkstyle/dark/rc/branch_more.png \
		qdarkstyle/dark/rc/transparent_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical.png \
		qdarkstyle/dark/rc/line_horizontal_focus.png \
		qdarkstyle/dark/rc/window_minimize_focus.png \
		qdarkstyle/dark/rc/checkbox_indeterminate@2x.png \
		qdarkstyle/dark/rc/branch_end_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_up_pressed.png \
		qdarkstyle/dark/rc/arrow_right.png \
		qdarkstyle/dark/rc/radio_checked_disabled@2x.png \
		qdarkstyle/dark/rc/branch_open_pressed.png \
		qdarkstyle/dark/rc/line_horizontal_disabled.png \
		qdarkstyle/dark/rc/window_close_focus.png \
		qdarkstyle/dark/rc/radio_checked_disabled.png \
		qdarkstyle/dark/rc/branch_more@2x.png \
		qdarkstyle/dark/rc/branch_open.png \
		qdarkstyle/dark/rc/checkbox_unchecked_disabled@2x.png \
		qdarkstyle/dark/rc/base_icon_focus@2x.png \
		qdarkstyle/dark/rc/checkbox_unchecked_pressed.png \
		qdarkstyle/dark/rc/window_close_focus@2x.png \
		qdarkstyle/dark/rc/window_minimize_pressed@2x.png \
		qdarkstyle/dark/rc/branch_closed.png \
		qdarkstyle/dark/rc/arrow_up_focus@2x.png \
		qdarkstyle/dark/rc/radio_checked_pressed.png \
		qdarkstyle/dark/rc/branch_end_disabled@2x.png \
		qdarkstyle/dark/rc/radio_unchecked_disabled@2x.png \
		qdarkstyle/dark/rc/radio_unchecked_focus@2x.png \
		qdarkstyle/dark/rc/base_icon@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_pressed.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_disabled.png \
		qdarkstyle/dark/rc/branch_line_disabled@2x.png \
		qdarkstyle/dark/rc/branch_closed_pressed.png \
		qdarkstyle/dark/rc/branch_closed_focus@2x.png \
		qdarkstyle/dark/rc/window_minimize@2x.png \
		qdarkstyle/dark/rc/window_minimize.png \
		qdarkstyle/dark/rc/transparent_pressed.png \
		qdarkstyle/dark/rc/window_grip@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_pressed@2x.png \
		qdarkstyle/dark/rc/base_icon_focus.png \
		qdarkstyle/dark/rc/checkbox_checked_pressed.png \
		qdarkstyle/dark/rc/arrow_down_focus.png \
		qdarkstyle/dark/rc/radio_checked.png \
		qdarkstyle/dark/rc/branch_end_disabled.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_pressed.png \
		qdarkstyle/dark/rc/radio_unchecked_focus.png \
		qdarkstyle/dark/rc/window_undock_focus@2x.png \
		qdarkstyle/dark/rc/radio_unchecked_pressed.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_disabled.png \
		qdarkstyle/dark/rc/window_undock.png \
		qdarkstyle/dark/rc/window_grip_disabled.png \
		qdarkstyle/dark/rc/branch_open_pressed@2x.png \
		qdarkstyle/dark/rc/radio_checked_focus.png \
		qdarkstyle/dark/rc/checkbox_checked_focus.png \
		qdarkstyle/dark/rc/window_undock_pressed@2x.png \
		qdarkstyle/dark/rc/line_vertical_disabled.png \
		qdarkstyle/dark/rc/checkbox_unchecked_focus.png \
		qdarkstyle/dark/rc/branch_closed_focus.png \
		qdarkstyle/dark/rc/arrow_down@2x.png \
		qdarkstyle/dark/rc/toolbar_move_vertical_focus@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_focus.png \
		qdarkstyle/dark/rc/window_grip_disabled@2x.png \
		qdarkstyle/dark/rc/radio_unchecked.png \
		qdarkstyle/dark/rc/checkbox_unchecked_pressed@2x.png \
		qdarkstyle/dark/rc/window_grip.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical@2x.png \
		qdarkstyle/dark/rc/arrow_right_focus.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_focus@2x.png \
		qdarkstyle/dark/rc/transparent_disabled@2x.png \
		qdarkstyle/dark/rc/base_icon_disabled@2x.png \
		qdarkstyle/dark/rc/window_grip_pressed.png \
		qdarkstyle/dark/rc/base_icon.png \
		qdarkstyle/dark/rc/transparent@2x.png \
		qdarkstyle/dark/rc/arrow_up@2x.png \
		qdarkstyle/dark/rc/line_vertical_pressed@2x.png \
		qdarkstyle/dark/rc/line_horizontal_disabled@2x.png \
		qdarkstyle/dark/rc/window_minimize_disabled@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_disabled.png \
		qdarkstyle/dark/rc/window_minimize_focus@2x.png \
		qdarkstyle/dark/rc/window_undock@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_disabled@2x.png \
		qdarkstyle/dark/rc/branch_line_pressed@2x.png \
		qdarkstyle/dark/rc/branch_line_focus@2x.png \
		qdarkstyle/dark/rc/branch_line_pressed.png \
		qdarkstyle/dark/rc/window_minimize_pressed.png \
		qdarkstyle/dark/rc/radio_unchecked@2x.png \
		qdarkstyle/dark/rc/checkbox_indeterminate_focus.png \
		qdarkstyle/dark/rc/branch_closed_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_left.png \
		qdarkstyle/dark/rc/toolbar_separator_vertical_pressed@2x.png \
		qdarkstyle/dark/rc/branch_more_focus@2x.png \
		qdarkstyle/dark/rc/line_horizontal_pressed@2x.png \
		qdarkstyle/dark/rc/branch_more_pressed.png \
		qdarkstyle/dark/rc/arrow_right_pressed.png \
		qdarkstyle/dark/rc/arrow_down_pressed@2x.png \
		qdarkstyle/dark/rc/toolbar_separator_horizontal_pressed.png \
		qdarkstyle/dark/rc/branch_closed@2x.png \
		qdarkstyle/dark/rc/branch_end@2x.png \
		qdarkstyle/dark/rc/arrow_left_disabled.png \
		qdarkstyle/dark/rc/transparent_disabled.png \
		qdarkstyle/dark/rc/branch_open_disabled.png \
		qdarkstyle/dark/rc/branch_open_focus.png \
		qdarkstyle/dark/rc/arrow_down_disabled.png \
		qdarkstyle/dark/rc/radio_unchecked_pressed@2x.png \
		qdarkstyle/dark/rc/branch_end.png \
		qdarkstyle/dark/rc/checkbox_unchecked_disabled.png \
		qdarkstyle/dark/rc/checkbox_checked_focus@2x.png \
		qdarkstyle/dark/rc/arrow_left_pressed.png \
		qdarkstyle/dark/rc/arrow_down.png \
		qdarkstyle/dark/rc/toolbar_move_horizontal_pressed@2x.png \
		qdarkstyle/dark/rc/arrow_right_focus@2x.png \
		qdarkstyle/dark/style.qss
	/opt/Qt/5.15.2/gcc_64/bin/rcc -name style qdarkstyle/dark/style.qrc -o qrc_style.cpp

qrc_icons.cpp: icons/icons.qrc \
		/opt/Qt/5.15.2/gcc_64/bin/rcc \
		icons/megaman_petit2.png
	/opt/Qt/5.15.2/gcc_64/bin/rcc -name icons icons/icons.qrc -o qrc_icons.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /opt/Qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qicon.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QTimer \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QSlider \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QAction \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothaddress.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qtbluetoothglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qtbluetooth-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QByteArray \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QString \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QMetaType \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothserviceinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothUuid \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothuuid.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QtGlobal \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QUuid \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/quuid.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothAddress \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QList \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QSharedPointer \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QVariant \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothserver.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetooth.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothSocket \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothsocket.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothServiceInfo \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QSystemTrayIcon \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		libMPSSE_spi.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/gcc_64/bin/moc
	/opt/Qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include /home/ben/STB032_SPI/moc_predefs.h -I/opt/Qt/5.15.2/gcc_64/mkspecs/linux-g++ -I/home/ben/STB032_SPI -I/opt/Qt/5.15.2/gcc_64/include -I/opt/Qt/5.15.2/gcc_64/include/QtWidgets -I/opt/Qt/5.15.2/gcc_64/include/QtGui -I/opt/Qt/5.15.2/gcc_64/include/QtBluetooth -I/opt/Qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/12.2.0 -I/usr/include/c++/12.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/12.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/opt/Qt/5.15.2/gcc_64/bin/uic
	/opt/Qt/5.15.2/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qicon.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QTimer \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QSlider \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QAction \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothaddress.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qtbluetoothglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qtbluetooth-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QByteArray \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QString \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QMetaType \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothserviceinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothUuid \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothuuid.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QtGlobal \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QUuid \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/quuid.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothAddress \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QList \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QSharedPointer \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QVariant \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothserver.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetooth.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothSocket \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothsocket.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothServiceInfo \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QSystemTrayIcon \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		libMPSSE_spi.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qinputmethod.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QFile
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ftdi_common.o: ftdi_common.c ftdi_infra.h \
		ftdi_common.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftdi_common.o ftdi_common.c

ftdi_i2c.o: ftdi_i2c.c ftdi_infra.h \
		ftdi_common.h \
		ftdi_i2c.h \
		ftdi_mid.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftdi_i2c.o ftdi_i2c.c

ftdi_infra.o: ftdi_infra.c ftdi_infra.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftdi_infra.o ftdi_infra.c

ftdi_mid.o: ftdi_mid.c ftdi_infra.h \
		ftdi_common.h \
		ftdi_mid.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftdi_mid.o ftdi_mid.c

ftdi_spi.o: ftdi_spi.c ftdi_infra.h \
		ftdi_common.h \
		ftdi_spi.h \
		ftdi_mid.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ftdi_spi.o ftdi_spi.c

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qrect.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qregion.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qline.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qimage.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfont.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qevent.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qset.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qicon.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QTimer \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QSlider \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qslider.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qabstractslider.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QAction \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qaction.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qactiongroup.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothaddress.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qtbluetoothglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qtbluetooth-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QByteArray \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QString \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QMetaType \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothserviceinfo.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothUuid \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothuuid.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QtGlobal \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QUuid \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/quuid.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QDebug \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothAddress \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QList \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QSharedPointer \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QVariant \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothserver.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QObject \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetooth.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothSocket \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothsocket.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/opt/Qt/5.15.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothServiceInfo \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QSystemTrayIcon \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qsystemtrayicon.h \
		libMPSSE_spi.h \
		ui_mainwindow.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QFile \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QThread \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qthread.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/qelapsedtimer.h \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/QMenu \
		/opt/Qt/5.15.2/gcc_64/include/QtWidgets/qmenu.h \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/QScreen \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/qscreen.h \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QRect \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QSize \
		/opt/Qt/5.15.2/gcc_64/include/QtCore/QSizeF \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/QTransform \
		/opt/Qt/5.15.2/gcc_64/include/QtGui/QKeyEvent \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothlocaldevice.h \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/QBluetoothHostInfo \
		/opt/Qt/5.15.2/gcc_64/include/QtBluetooth/qbluetoothhostinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_style.o: qrc_style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_style.o qrc_style.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

